name: CI Verification

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    branches: [ "release/**" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install Cairo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config python3-dev

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pip-audit

    - name: Set up Environment
      run: cp .env.example .env.dev

    - name: Run Package Audit
      run: pip-audit --ignore-vuln CVE-2024-25885

    - name: Make Migrations
      run: python manage.py makemigrations --noinput

    - name: Run Tests
      run: python manage.py test
